server:
  port: 8130
spring:
  redis:
    password: 123456
    database: 1
    port: 6379
    jedis:
      pool:
        max-idle: 10
        min-idle: 0
        max-active: 200
        max-wait: -1
    host: 150.158.100.96
    timeout: 1000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://150.158.100.96:3306/impeach?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123456
    #连接池类型改为druid
    type: com.alibaba.druid.pool.DruidDataSource
    #初始化连接数
    druid.initial-size: 10
    #最小连接数
    druid.min-idle: 100
    #最大连接数
    druid.max-active: 1000
    #获取连接时最大等待时间，单位毫秒
    druid.max-wait: 60000
    #检测连接是否有效
    druid.validation-query: SELECT 1 FROM DUAL
    druid.test-on-borrow: false
    druid.test-on-return: false
    #检查空闲连接有效性
    druid.test-while-idle: true
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    druid.time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    druid.min-victable-idle-time-millis: 300000
    #查询超时时间 单位是毫秒
    druid.query-timeout: 60000
    #保持连接活动
    #druid.keep-alive: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录:单位秒
    druid.connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  cloud:
    nacos:
      discovery:
        server-addr: 172.21.32.104:8848
#        register-enabled: false
logging:
  level:
    com.youmatech.zhsq.login.dao: DEBUG

